services:
  nginx: # name of service
    container_name: evt-challenge # custom name for docker container
    build:
      context: . # use Dockerfile in current directory
    ports:
      - 8443:443
    volumes:
      - ./html/:/usr/share/nginx/html/ # mount the local html directory to the nginx html directory
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf # mount the local nginx directory to the nginx
      - ./certs:/certs:ro
