services:
  nginx: # name of service
    container_name: evt-challenge # custom name for docker container
    build:
      context: . # use Dockerfile in current directory
    ports:
      - 8000:80 # localhost:8000/
    volumes:
      - ./html/:/usr/share/nginx/html/ # mount the local html directory to the nginx html directory
      - ./nginx/:/etc/nginx/nginx/ # mount the local nginx directory to the nginx
