services:
  nginx: # name of service
    container_name: evt-challenge # custom name for docker container
    build:
      context: . # use Dockerfile in current directory
    ports:
      - 8443:443
    volumes:
      - ./html/:/usr/share/nginx/html/
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/certs:ro
